---
- name: Create symlink for let's encrypt ssl cert
  file:
    src: "{{ letsencrypt_cert_path }}"
    dest: "{{ nginx_cert_path }}"
    state: link
  when: nginx_enable_ssl
  notify:
    - Restart nginx
  tags:
    - nginx

- name: Create symlink for let's encrypt ssl key
  file:
    src: "{{ letsencrypt_key_path }}"
    dest: "{{ nginx_key_path }}"
    state: link
    mode: 0600
  notify:
    - Restart nginx
  when: nginx_enable_ssl
  tags:
    - nginx

- name: Create root directory for let's encrypt
  file:
    path: "/var/www/letsencrypt"
    state: directory
  when: nginx_enable_ssl
  tags:
    - nginx

- name: Remove default.conf vhost
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  when: nginx_vhost != 'default'
  tags:
    - nginx

- name: Deliver vhost
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
  notify:
    - Restart nginx
  with_items:
    - "{{ nginx_vhost }}"
  when: nginx_vhost != 'default'
  tags:
    - nginx
